### ISSUE TITLE
[QUESTION]: is this using bootstrap or tailwind? or even mixed? looks both is in the package.json

### ISSUE THREAD

**Issue by akunbeben** [zuramai/laravel-mazer#11]
I want to use this laravel boilerplate, but I got a bit confused about the dependencies. 

If we take a look in the origin [mazer](https://github.com/zuramai/mazer) template, it's no tailwind there.
but in this repository using tailwind, it's even compiled

**Comment by vanvanni** [comment]
Agreed. I was just having the same confusion and therefore visiting the issues page. Would love to see it still shipped with BS5(.2) rather then tailwind. Or run a first time mazer:install with a preset flag. Would be nice to have some clarification. Developers might be able to contribute this :)
