### ISSUE TITLE
[QUESTION] Does we need add mix build artifacts(include mix-manifest.json)?

### ISSUE THREAD

**Issue by dipras** [zuramai/laravel-mazer#17]
For now, in this repository we don't add mix build artifact to .gitignore. It will be annoying when we commit because the artifacts are still being detected as "uncommitted files". Even we commit the artifacts and push it to repository, other people who pulled it will need rebuild again and face the same problem right?

**Comment by zuramai** [comment]
You're right. Actually, we haven't upgrade this laravel version of mazer to the current latest Mazer version yet (v2.1) which is using Vite instead of Laravel Mix. Hence we need to upgrade to upgrade it to the latest version of mazer to avoid the laravel mix problem.

**Comment by dipras** [comment]
Ah, that's good. Okay, I will try to upgrade this repository to use vite instead of laravel mix
I will make Pull Request to solve this issue

**Comment by dipras** [comment]
Okay, the pull request is merged so this issue is done
